### ISSUE TITLE
/moss permission check for roles and location

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/CSE-Discord-Bot#270]
`/moss` and `/moss-register` needs to be limited to staff / faculty / TA / devteam and should only work in `#ta-moss`

**Comment by BPennie03** [comment]
Just found out this can be completely done in discord settings. To do so:

- Go to desired server
- Go to Server Settings > Integrations 
- Go to desired bot and click `Manage`
- Here you can add specific command overrides for both channels and users/roles.

This is helpful because the implementation I was going towards didn't hide the roles from everyone, just simply didn't allow it to be run. And since it isn't an "Admin Command" it would show up to students, but wouldn't allow them to run it. If we configure it in the server settings, it properly hides the commands and prevents execution to people with unsupported roles or in an improper channel. 

I would like to discuss with everyone which way we should approach this

**Comment by BPennie03** [comment]
We changed these settings server-side, so no additional code was needed and this is now complete
