### ISSUE TITLE
"Application did not Respond" error message when running admin `checkin-report-monthly`

### ISSUE THREAD

**Issue by bibekrj** [wrightedu/CSE-Discord-Bot#412]
When the `checkin-report-monthly` function is run, the bot responds with "application did not respond" error. 

While the report text file is indeed generated and returned to the user. The application seems to time out and also generate the error in tandem.

**Comment by JakeHamblin** [comment]
Has been resolved in the `checkin-generate-admin-report` branch. The problem was that the report monthly would not return a response unless there was an impossible case. Interaction is now deferred, which allows for a longer response time. Response messages have also been set, with the file returned being sent in the ephemeral interaction response.
